/**
 * Voila Test Authentication System - Development/Testing JWT tokens ONLY
 * @file src/lib/test-auth.ts
 * 
 * @llm-rule WHEN: Need authentication tokens for DEVELOPMENT and TESTING only
 * @llm-rule AVOID: Using this in production code - this is for dev/test environments only
 * @llm-rule PATTERN: Loads test tokens from .env.auth (gitignored, dev-only file)
 * @llm-rule WARNING: DO NOT USE IN PRODUCTION - Production needs real user auth flow
 * @llm-rule NOTE: Integrates with `npm run generate tokens` for test token generation
 */

// Browser-safe imports - only import fs/path in Node.js environment
let readFileSync: any, join: any;
if (typeof window === 'undefined') {
  // Server environment
  readFileSync = require('fs').readFileSync;
  join = require('path').join;
}

// ========================================
// TOKEN TYPE DEFINITIONS
// ========================================

export interface AuthTokens {
  // Login tokens (user authentication)
  ADMIN_SYSTEM: string;
  ADMIN_ORG: string;
  ADMIN_TENANT: string;
  MODERATOR_MANAGE: string;
  MODERATOR_APPROVE: string;
  MODERATOR_REVIEW: string;
  USER_MAX: string;
  USER_PRO: string;
  USER_BASIC: string;
  
  // API tokens (service authentication)  
  WEBHOOK_SERVICE_API_TOKEN: string;
}

export type TokenName = keyof AuthTokens;

export interface TokenInfo {
  name: TokenName;
  role: 'admin' | 'moderator' | 'user' | 'service';
  level: 'system' | 'org' | 'tenant' | 'manage' | 'approve' | 'review' | 'max' | 'pro' | 'basic';
  type: 'login' | 'api';
  description: string;
}

// ========================================
// TOKEN METADATA
// ========================================

export const TOKEN_METADATA: Record<TokenName, TokenInfo> = {
  // Admin tokens
  ADMIN_SYSTEM: { name: 'ADMIN_SYSTEM', role: 'admin', level: 'system', type: 'login', description: 'System-wide admin access' },
  ADMIN_ORG: { name: 'ADMIN_ORG', role: 'admin', level: 'org', type: 'login', description: 'Organization admin access' },
  ADMIN_TENANT: { name: 'ADMIN_TENANT', role: 'admin', level: 'tenant', type: 'login', description: 'Tenant admin access' },
  
  // Moderator tokens
  MODERATOR_MANAGE: { name: 'MODERATOR_MANAGE', role: 'moderator', level: 'manage', type: 'login', description: 'Content management access' },
  MODERATOR_APPROVE: { name: 'MODERATOR_APPROVE', role: 'moderator', level: 'approve', type: 'login', description: 'Content approval access' },
  MODERATOR_REVIEW: { name: 'MODERATOR_REVIEW', role: 'moderator', level: 'review', type: 'login', description: 'Content review access' },
  
  // User tokens
  USER_MAX: { name: 'USER_MAX', role: 'user', level: 'max', type: 'login', description: 'Maximum user privileges' },
  USER_PRO: { name: 'USER_PRO', role: 'user', level: 'pro', type: 'login', description: 'Professional user access' },
  USER_BASIC: { name: 'USER_BASIC', role: 'user', level: 'basic', type: 'login', description: 'Basic user access' },
  
  // API tokens
  WEBHOOK_SERVICE_API_TOKEN: { name: 'WEBHOOK_SERVICE_API_TOKEN', role: 'service', level: 'system', type: 'api', description: 'Webhook service API access' }
};

// ========================================
// TOKEN LOADING (PRODUCTION)
// ========================================

let cachedTokens: AuthTokens | null = null;

/**
 * Parse .env.auth file and extract TEST tokens for development/testing
 * This reads test tokens generated by `npm run generate tokens`
 * WARNING: Only for development/testing - not for production use
 */
export function loadAuthTokens(envAuthPath?: string): AuthTokens {
  if (cachedTokens) {
    return cachedTokens;
  }

  let authFilePath = envAuthPath;
  
  if (!authFilePath) {
    if (typeof process !== 'undefined' && process.cwd) {
      authFilePath = join(process.cwd(), '.env.auth');
    } else if (typeof window !== 'undefined') {
      throw new Error('Browser environment requires envAuthPath parameter or build-time token injection');
    } else {
      throw new Error('Unable to auto-detect .env.auth file location');
    }
  }

  // Skip file reading in browser environment
  if (typeof window !== 'undefined') {
    throw new Error('Browser environment: Auth tokens should be provided via environment variables or build-time injection');
  }

  if (!readFileSync) {
    throw new Error('File system not available in this environment');
  }

  try {
    const authFileContent = readFileSync(authFilePath, 'utf-8');
    const tokens: Partial<AuthTokens> = {};
    
    authFileContent.split('\n').forEach(line => {
      const trimmedLine = line.trim();
      if (!trimmedLine || trimmedLine.startsWith('#')) return;
      
      const equalIndex = trimmedLine.indexOf('=');
      if (equalIndex === -1) return;
      
      const key = trimmedLine.substring(0, equalIndex).trim();
      const value = trimmedLine.substring(equalIndex + 1).trim();
      
      if (key in TOKEN_METADATA) {
        (tokens as any)[key] = value;
      }
    });
    
    // Validate all tokens are present, fill missing with defaults
    const missingTokens = Object.keys(TOKEN_METADATA).filter(key => !tokens[key as TokenName]);
    
    if (missingTokens.length > 0) {
      console.warn(`⚠️ Missing tokens in .env.auth: ${missingTokens.join(', ')}`);
      console.warn('💡 Run: npm run generate tokens');
      
      // Fill missing with fallback tokens
      missingTokens.forEach(key => {
        (tokens as any)[key] = getFallbackTokens()[key as TokenName];
      });
    }
    
    cachedTokens = tokens as AuthTokens;
    return cachedTokens;
    
  } catch (error) {
    console.error('❌ Failed to read .env.auth file:', error);
    console.log('🔄 Using fallback development tokens');
    console.log('💡 Run: npm run generate tokens');
    
    cachedTokens = getFallbackTokens();
    return cachedTokens;
  }
}

/**
 * Get specific token by name
 */
export function getAuthToken(tokenName: TokenName, envAuthPath?: string): string {
  // Browser environment - use Vite environment variables
  if (typeof window !== 'undefined') {
    const browserTokens: AuthTokens = {
      'WEBHOOK_SERVICE_API_TOKEN': import.meta.env.VITE_WEBHOOK_SERVICE_API_TOKEN,
      'USER_BASIC': import.meta.env.VITE_USER_BASIC,
      'ADMIN_TENANT': import.meta.env.VITE_ADMIN_TENANT,
      'ADMIN_SYSTEM': import.meta.env.VITE_ADMIN_SYSTEM,
      'ADMIN_ORG': import.meta.env.VITE_ADMIN_ORG,
      'MODERATOR_MANAGE': import.meta.env.VITE_MODERATOR_MANAGE,
      'MODERATOR_APPROVE': import.meta.env.VITE_MODERATOR_APPROVE,
      'MODERATOR_REVIEW': import.meta.env.VITE_MODERATOR_REVIEW,
      'USER_MAX': import.meta.env.VITE_USER_MAX,
      'USER_PRO': import.meta.env.VITE_USER_PRO
    };
    return browserTokens[tokenName];
  }
  
  const tokens = loadAuthTokens(envAuthPath);
  return tokens[tokenName];
}

/**
 * Clear token cache (useful for testing)
 */
export function clearTokenCache(): void {
  cachedTokens = null;
}

// ========================================
// TOKEN HELPERS (CONVENIENT ACCESS)
// ========================================

export const AuthTokenHelpers = {
  // Most common tokens for greeting feature
  getApiToken: () => getAuthToken('WEBHOOK_SERVICE_API_TOKEN'),
  getUserToken: () => getAuthToken('USER_BASIC'),
  getAdminToken: () => getAuthToken('ADMIN_TENANT'),
  
  // All role-based tokens
  getAdminSystemToken: () => getAuthToken('ADMIN_SYSTEM'),
  getAdminOrgToken: () => getAuthToken('ADMIN_ORG'),
  getModeratorToken: () => getAuthToken('MODERATOR_MANAGE'),
  getUserMaxToken: () => getAuthToken('USER_MAX'),
  getUserProToken: () => getAuthToken('USER_PRO'),
  
  // For testing - get multiple tokens at once
  getTestTokenSet: () => ({
    apiToken: getAuthToken('WEBHOOK_SERVICE_API_TOKEN'),
    userToken: getAuthToken('USER_BASIC'),
    adminToken: getAuthToken('ADMIN_TENANT'),
    moderatorToken: getAuthToken('MODERATOR_MANAGE')
  }),
  
  // Get token metadata
  getTokenInfo: (tokenName: TokenName) => TOKEN_METADATA[tokenName],
  
  // List all available tokens
  getAllTokens: () => loadAuthTokens(),
  getAllTokenNames: () => Object.keys(TOKEN_METADATA) as TokenName[]
};

// ========================================
// FALLBACK TOKENS (DEVELOPMENT)
// ========================================

/**
 * Fallback development tokens (when .env.auth is not available)
 * These are safe defaults for development/testing
 * Note: These should match the latest generated tokens in .env.auth
 */
function getFallbackTokens(): AuthTokens {
  return {

    ADMIN_SYSTEM: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbl9zeXN0ZW0iLCJyb2xlIjoiYWRtaW4iLCJsZXZlbCI6InN5c3RlbSIsInR5cGUiOiJsb2dpbiIsImlhdCI6MTc1NzAzNTQyNywiZXhwIjoxNzU3NjQwMjI3fQ.AhLCAP_8qkdCtE3mwIb-pYVPu758pZiIku0EapCyXJ8',
    ADMIN_ORG: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbl9vcmciLCJyb2xlIjoiYWRtaW4iLCJsZXZlbCI6Im9yZyIsInR5cGUiOiJsb2dpbiIsImlhdCI6MTc1NzAzNTQyNywiZXhwIjoxNzU3NjQwMjI3fQ.ojNdfW0V0_ChrYKWiEd3z7Wlz1s9cMuYweNinkSxN3A',
    ADMIN_TENANT: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJhZG1pbl90ZW5hbnQiLCJyb2xlIjoiYWRtaW4iLCJsZXZlbCI6InRlbmFudCIsInR5cGUiOiJsb2dpbiIsImlhdCI6MTc1NzAzNTQyNywiZXhwIjoxNzU3NjQwMjI3fQ.4UEtjSp15LuH3pJ2DCmqLb2vP9OVIbVOwYPDvTCSfSM',
    MODERATOR_MANAGE: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJtb2RlcmF0b3JfbWFuYWdlIiwicm9sZSI6Im1vZGVyYXRvciIsImxldmVsIjoibWFuYWdlIiwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzU3MDM1NDI3LCJleHAiOjE3NTc2NDAyMjd9.rUsiW7DUWZmxTpyHH6xoxLG65oZKhtxFenJnS00H6bA',
    MODERATOR_APPROVE: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJtb2RlcmF0b3JfYXBwcm92ZSIsInJvbGUiOiJtb2RlcmF0b3IiLCJsZXZlbCI6ImFwcHJvdmUiLCJ0eXBlIjoibG9naW4iLCJpYXQiOjE3NTcwMzU0MjcsImV4cCI6MTc1NzY0MDIyN30.-g9tgejxXjmzWEaPo3GdUddRXTnYxwwjHRRoQXLR5Pg',
    MODERATOR_REVIEW: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJtb2RlcmF0b3JfcmV2aWV3Iiwicm9sZSI6Im1vZGVyYXRvciIsImxldmVsIjoicmV2aWV3IiwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzU3MDM1NDI3LCJleHAiOjE3NTc2NDAyMjd9.oo4sNqsrkegagvj5cHFGGzzW-7viJFyeDfgc1ghzR8Q',
    USER_MAX: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX21heCIsInJvbGUiOiJ1c2VyIiwibGV2ZWwiOiJtYXgiLCJ0eXBlIjoibG9naW4iLCJpYXQiOjE3NTcwMzU0MjcsImV4cCI6MTc1NzY0MDIyN30.x8Laq7gWdZSGYXoRG09jL5gOVIe9Uv5UvdwqQ9k2ih8',
    USER_PRO: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX3BybyIsInJvbGUiOiJ1c2VyIiwibGV2ZWwiOiJwcm8iLCJ0eXBlIjoibG9naW4iLCJpYXQiOjE3NTcwMzU0MjcsImV4cCI6MTc1NzY0MDIyN30.4MkW4ilWUIyp9-0Ejp7GNmiP4cmcJ_RI4ZwiIFuENxU',
    USER_BASIC: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJ1c2VyX2Jhc2ljIiwicm9sZSI6InVzZXIiLCJsZXZlbCI6ImJhc2ljIiwidHlwZSI6ImxvZ2luIiwiaWF0IjoxNzU3MDM1NDI3LCJleHAiOjE3NTc2NDAyMjd9.lONjDB6-OtEksF0q-eeLdlTO1s_AoApXZDid2mY9Wow',
    WEBHOOK_SERVICE_API_TOKEN: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJrZXlJZCI6IndlYmhvb2tfc2VydmljZSIsInJvbGUiOiJhZG1pbiIsImxldmVsIjoic3lzdGVtIiwidHlwZSI6ImFwaV9rZXkiLCJpYXQiOjE3NTcwMzU0MjcsImV4cCI6MTc4ODU5MzAyN30.j_wpPTY5JhGii-m9sO6Xi0RE69A03fc6aETVoM8HXVE',
  }
}

// ========================================
// MOCK HELPERS FOR TESTING
// ========================================

// Import for type definitions (conditional import to avoid circular dependencies)
type HelloResponse = {
  success: boolean;
  data: {
    greetings: string[];
    name: string;
    language_count: number;
    timestamp: string;
    requestId: string;
    feature: string;
  };
};

export const mockHelloResponses = {
  default: {
    success: true,
    data: {
      greetings: ['Hello World!', 'Hola Mundo!', 'Bonjour le Monde!'],
      name: 'World',
      language_count: 3,
      timestamp: '2025-09-04T08:00:00.000Z',
      requestId: 'mock-default-123',
      feature: 'hello'
    }
  } as HelloResponse,

  personal: (name: string = 'TestUser') => ({
    success: true,
    data: {
      greetings: [`Hello ${name}!`, `Hola ${name}!`, `Bonjour ${name}!`],
      name: name,
      language_count: 3,
      timestamp: '2025-09-04T08:00:00.000Z',
      requestId: `mock-personal-${name.toLowerCase()}-123`,
      feature: 'hello'
    }
  } as HelloResponse),

  goodDay: {
    success: true,
    data: {
      greetings: ['Good day!', '¡Buen día!', 'Bonne journée!'],
      name: 'Good Day',
      language_count: 3,
      timestamp: '2025-09-04T08:00:00.000Z',
      requestId: 'mock-goodday-123',
      feature: 'hello'
    }
  } as HelloResponse,

  thankYou: {
    success: true,
    data: {
      greetings: ['Thank you!', '¡Gracias!', 'Merci!'],
      name: 'Thank You',
      language_count: 3,
      timestamp: '2025-09-04T08:00:00.000Z',
      requestId: 'mock-thankyou-123',
      feature: 'hello'
    }
  } as HelloResponse
};

/**
 * Create mock React Query result
 */
export function createMockQueryResult<T>(data: T, options: {
  isLoading?: boolean;
  error?: Error | null;
  isSuccess?: boolean;
  isError?: boolean;
} = {}) {
  return {
    data,
    isLoading: options.isLoading ?? false,
    error: options.error ?? null,
    isSuccess: options.isSuccess ?? true,
    isError: options.isError ?? false,
    isPending: options.isLoading ?? false,
    status: options.isLoading ? 'pending' : options.isError ? 'error' : 'success',
    refetch: () => Promise.resolve(),
  };
}

/**
 * Mock useVoilaApi hook
 */
export const mockUseVoilaApi = (responses: Record<string, any> = {}) => {
  const mockGetFn = (endpoint: string) => {
    if (endpoint === '/hello') return createMockQueryResult(mockHelloResponses.default);
    if (endpoint === '/hello/goodday') return createMockQueryResult(mockHelloResponses.goodDay);
    if (endpoint === '/hello/thankyou') return createMockQueryResult(mockHelloResponses.thankYou);
    if (endpoint.startsWith('/hello/')) {
      const name = endpoint.replace('/hello/', '');
      return createMockQueryResult(mockHelloResponses.personal(name));
    }
    if (responses[endpoint]) return createMockQueryResult(responses[endpoint]);
    return createMockQueryResult(null);
  };
  
  return {
    get: mockGetFn,
    invalidateQueries: () => Promise.resolve()
  };
};